CREATE DATABASE quarkus-social;

CREATE TABLE "user" (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	AGE INTEGER NOT NULL
);

CREATE TABLE post(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	TEXT VARCHAR(150) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL,
	USER_ID BIGINT NOT NULL REFERENCES "user"(ID)
);

CREATE TABLE follower(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	USER_ID BIGINT NOT NULL REFERENCES "user"(ID),
	FOLLOWER_ID BIGINT NOT NULL REFERENCES "user"(ID)
);